#!/bin/bash

#获取信息
dt_input(){

while [[ -z ${user} ]]; do
    user=$(whiptail --inputbox --nocancel "输入用户名（准备安装Clash的非root用户）" 8 78 --title "创建非root用户" 3>&1 1>&2 2>&3)
done

while [[ -z ${password} ]]; do
    password=$(whiptail --inputbox --nocancel "输入密码" 8 78 --title "创建密码" 3>&1 1>&2 2>&3)
done

while [[ -z ${loc_ip} ]]; do
    loc_ip=$(whiptail --inputbox --nocancel "输入本机IP（现在安装Clash机器的ip）" 8 78 --title "本机IP" 3>&1 1>&2 2>&3)
done

while [[ -z ${gate_ip} ]]; do
    gate_ip=$(whiptail --inputbox --nocancel "输入网关IP（输入网关IP（主路由）" 8 78 --title "网关IP" 3>&1 1>&2 2>&3)
done

while [[ -z ${dns} ]]; do
    dns=$(whiptail --inputbox --nocancel "输入dns（随你喜欢）" 8 78 --title "dns" 3>&1 1>&2 2>&3)
done

while [[ -z ${config} ]]; do
    config=$(whiptail --inputbox --nocancel "输入链接（仅测试墙洞）" 8 78 --title "Clash托管连接" 3>&1 1>&2 2>&3)
done

while [[ -z ${port} ]]; do
    port=$(whiptail --inputbox --nocancel "输入控制面板端口（例如9090）" 8 78 --title "控制面板端口" 3>&1 1>&2 2>&3)
done

while [[ -z ${secret} ]]; do
    secret=$(whiptail --inputbox --nocancel "输入控制面板密码（例如9090）" 8 78 --title "控制面板密码" 3>&1 1>&2 2>&3)
done
}

dt_system_dep(){

yes|apt -y install sudo supervisor iptables-persistent net-tools curl gzip unzip

useradd -m -s /bin/bash $user

echo $user:$password|chpasswd

usermod -aG sudo $user

echo " ">>/etc/sysctl.conf
echo "# made ipv4-forward in $(date +%F)">>/etc/sysctl.conf
echo 'net.ipv4.ip_forward=1'>>/etc/sysctl.conf
echo " ">>/etc/sysctl.conf
echo 'fs.file-max = 999999'>>/etc/sysctl.conf
echo 'net.core.rmem_max = 67108864'>>/etc/sysctl.conf
echo 'net.core.wmem_max = 67108864'>>/etc/sysctl.conf
echo 'net.core.rmem_default = 6291456'>>/etc/sysctl.conf
echo 'net.core.wmem_default = 6291456'>>/etc/sysctl.conf
echo 'net.core.netdev_max_backlog = 65535'>>/etc/sysctl.conf
echo 'net.core.somaxconn = 262114'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_tw_reuse = 1'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_fin_timeout = 30'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_keepalive_time = 1200'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_max_syn_backlog = 8192'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_max_tw_buckets = 5000'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_mem = 8192 131072 67108864'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_rmem = 10240 87380 12582912'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_wmem = 10240 87380 12582912'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_mtu_probing = 1'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_notsent_lowat = 16384'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_syncookies = 1'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_max_orphans= 262114'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_fastopen = 3'>>/etc/sysctl.conf
echo 'net.ipv4.ip_local_port_range = 1024 65000'>>/etc/sysctl.conf
echo 'net.ipv4.udp_mem = 8192 131072 67108864'>>/etc/sysctl.conf
echo 'net.ipv4.udp_rmem_min = 4096'>>/etc/sysctl.conf
echo 'net.ipv4.udp_wmem_min = 4096'>>/etc/sysctl.conf
echo " ">>/etc/sysctl.conf
echo "# made bbr in $(date +%F)">>/etc/sysctl.conf
echo 'net.core.default_qdisc = fq'>>/etc/sysctl.conf
echo 'net.ipv4.tcp_congestion_control = bbr'>>/etc/sysctl.conf
echo " ">>/etc/sysctl.conf
echo "# made ipv6-disable in $(date +%F)">>/etc/sysctl.conf
echo 'net.ipv6.conf.all.disable_ipv6 = 1'>>/etc/sysctl.conf
echo 'net.ipv6.conf.default.disable_ipv6 = 1'>>/etc/sysctl.conf
echo 'net.ipv6.conf.lo.disable_ipv6 = 1'>>/etc/sysctl.conf
tail -5 /etc/sysctl.conf

sysctl -p

echo 'ListenAddress 0.0.0.0'>>/etc/ssh/sshd_config
echo 'AddressFamily inet'>>/etc/ssh/sshd_config

service sshd restart

echo 'DNSStubListener=no'>>/etc/systemd/resolved.conf
}


dt_clash(){


wget -O /opt/clash.gz $CLS
cd /opt

gzip -d clash.gz
mv clash /usr/bin/clash
chmod +x /usr/bin/clash
# 为 clash 添加绑定低位端口的权限，这样运行 clash 的时候无需 root 权限
setcap cap_net_bind_service=+ep /usr/bin/clash

mkdir -p /home/$user/.config/clash

cd /home/$user/.config/clash

wget -O config.yaml $config

sed -i '1d' config.yaml

sed -i '/^port/d' config.yaml

sed -i '/^socks-port/d' config.yaml

sed -i '/^redir-port/d' config.yaml

sed -i '/^allow-lan/d' config.yaml

sed -i '/^external-controller/d' config.yaml

sed -i '/^external-ui/d' config.yaml

sed -i '/^secret:/d' config.yaml

sed -i '1i port:7890' config.yaml

sed -i '/port:7890/a\socks-port:7891' config.yaml

sed -i '/socks-port:7891/a\redir-port:7892' config.yaml

sed -i '/redir-port:7892/a\allow-lan:true' config.yaml

sed -i '/allow-lan:true/a\external-controller:0.0.0.0:$port' config.yaml

sed -i '/external-controller:0.0.0.0/a\external-ui:dashboard' config.yaml

sed -i '/external-ui:dashboard/a\secret: "&secret"' config.yaml

wget https://github.com/haishanh/yacd/archive/gh-pages.zip

unzip gh-pages.zip

mv yacd-gh-pages/ dashboard/

chown -R $user /home/$user/.config/

cat << EOF > /etc/systemd/system/clash.service
[Unit]
Description=clash daemon
[Service]
Type=simple
User=$user
ExecStart=/usr/bin/clash -d /home/$user/.config/clash/
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF


systemctl daemon-reload
#设置自启动

systemctl start clash.service

systemctl enable clash.service

sleep 5
}


dt_iptables(){

temp_ip=(${loc_ip//./ })

jy_ip=${temp_ip[0]}"."${temp_ip[1]}".0.0"

iptables -A INPUT -i lo -j ACCEPT
echo "1******************************************************************"
iptables -A OUTPUT -o lo -j ACCEPT
echo "2******************************************************************"

iptables -t nat -N clash
echo "3******************************************************************"
iptables -t nat -N clash_dns
echo "4******************************************************************"
iptables -t nat -A PREROUTING -p tcp --dport 53 -d 198.18.0.0/24 -j clash_dns
echo "5******************************************************************"
iptables -t nat -A PREROUTING -p udp --dport 53 -d 198.18.0.0/24 -j clash_dns
echo "6******************************************************************"
iptables -t nat -A PREROUTING -p tcp -j clash
echo "7******************************************************************"

iptables -t nat -A clash_dns -p udp --dport 53 -d 198.18.0.0/24 -j DNAT --to-destination $loc_ip:53
echo "8******************************************************************"
iptables -t nat -A clash_dns -p tcp --dport 53 -d 198.18.0.0/24 -j DNAT --to-destination $loc_ip:53
echo "9******************************************************************"
#注意：这里的网段和IP你需要自己适配自己的
iptables -t nat -A clash -d 1.0.0.0/8 -j ACCEPT
iptables -t nat -A clash -d 10.0.0.0/8 -j ACCEPT
iptables -t nat -A clash -d 100.64.0.0/10 -j ACCEPT
iptables -t nat -A clash -d 127.0.0.0/8 -j ACCEPT
iptables -t nat -A clash -d 169.254.0.0/16 -j ACCEPT
iptables -t nat -A clash -d 172.16.0.0/12 -j ACCEPT
iptables -t nat -A clash -d 192.168.0.0/16 -j ACCEPT
iptables -t nat -A clash -d 224.0.0.0/4 -j ACCEPT
iptables -t nat -A clash -d 240.0.0.0/4 -j ACCEPT
iptables -t nat -A clash -d 192.168.1.2/32 -j ACCEPT
echo "10******************************************************************"
iptables -t nat -A clash -p tcp --dport 22 -d $loc_ip/24 -j ACCEPT
echo "11******************************************************************"
iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7892
echo "12******************************************************************"
netfilter-persistent save
echo "13******************************************************************"
netfilter-persistent start
echo "14******************************************************************"
iptables-save  > /etc/iptables/rules.v4
echo "15******************************************************************"
}


set_ip_dns(){

cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*
auto lo
iface lo inet loopback
auto  $eth_n
iface $eth_n inet static
  address $loc_ip
  netmask 255.255.255.0
  gateway $gate_ip
  dns-nameservers $dns
EOF

echo "14******************************************************************"
}

dt_menu() {
 Mainmenu=$(whiptail --clear --ok-button "确定" --backtitle "version:20200326" --title "Clash&SmartDNS一键安装" --menu --nocancel "
**********************************************************************************
简介：Clash一键安装
系统：>=debian10
详情：修改自油管UP主-米月大佬的“灯塔脚本”
原作者Youtube：米月
**********************************************************************************
请选择需要安装的内容：
    " 22 86 5\
        "1" " Clash一键安装"\
        "4" " 退出" 3>&1 1>&2 2>&3)
    case $Mainmenu in
        1)
        dt_input
        dt_system_dep        
        dt_clash
        dt_iptables
        set_ip_dns
        whiptail --title "Clash一键安装成功" --msgbox "
*************************************************************************
Clash安装成功，需要科学的设备请参照下面修改。软路由请自行修改。
设备网关：$loc_ip
设备DNS：198.18.0.1,198.18.0.2
Clash配置文件目录：/home/$user/.config/clash/config.yaml
Clash控制面板:http://$loc_ip:9090/ui/
灯塔原作者米月Youtube频道地址：https://t.im/n21o
Youtube：米月
电报群：https://t.me/mi_yue
*************************************************************************" 18 78
        clear
        ;;
        4)
        #exit
        clear
        whiptail --title "脚本已退出" --msgbox "真希望把你留住" 8 78
        ;;
        esac
}

eth_n=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)
GFW_LIST="https://raw.githubusercontent.com/pzwsquare/dt_client/master/black/gfw_domain.conf"
SM="https://github.com/pymumu/smartdns/releases/download/Release30/smartdns.1.2020.02.25-2212.x86_64-debian-all.deb"
CLS="https://github.com/Dreamacro/clash/releases/download/v0.19.0/clash-linux-amd64-v0.19.0.gz"

dt_menu
